services:
  db:
    image: postgres:latest
    container_name: financial_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: financial_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  # broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: financial_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Web

volumes:
  postgres_data:
